/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.philb.sampleui;

/**
 *
 * @author philb
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        navPanel1 = new ie.philb.sampleui.NavPanel();
        contentPanel1 = new ie.philb.sampleui.ContentPanel();

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setName("splitter"); // NOI18N

        navPanel1.setName("navPanel"); // NOI18N
        jSplitPane1.setLeftComponent(navPanel1);

        contentPanel1.setName("contentPanel"); // NOI18N
        jSplitPane1.setRightComponent(contentPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ie.philb.sampleui.ContentPanel contentPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private ie.philb.sampleui.NavPanel navPanel1;
    // End of variables declaration//GEN-END:variables


}
